apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging

resources:
  - namespace.yaml

helmCharts:
  - name: filebeat
    repo: https://helm.elastic.co
    releaseName: filebeat
    namespace: logging
    version: 8.5.1
    valuesFile: filebeat.values.yaml
  - name: logstash
    repo: https://helm.elastic.co
    releaseName: logstash
    namespace: logging
    version: 8.5.1
    valuesFile: logstash.values.yaml
  - name: elasticsearch
    repo: https://helm.elastic.co
    releaseName: elasticsearch
    namespace: logging
    version: 8.5.1
  - name: kibana
    repo: https://helm.elastic.co
    releaseName: kibana
    namespace: logging
    version: 8.5.1

patches:
  - target:
      kind: Secret
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/hook: Pre-Sync
          argocd.argoproj.io/sync-wave: "-10"
